---
repos:
    - hooks:
          - id: snakefmt
      repo: git@github.com:snakemake/snakefmt
      rev: v0.8.4
    - repo: git@github.com:pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: end-of-file-fixer
            exclude: \.Rd # sometimes roxygen fails to generate EOF blank line.
          - id: file-contents-sorter
            files: ^\.Rbuildignore$
    - repo: git@github.com:pre-commit/mirrors-mypy
      rev: v1.7.1  # Use the sha / tag you want to point at
      hooks:
          - id: mypy
            args: [--python-version=3.11, --ignore-missing-imports]
    - repo: git@github.com:jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/lorenzwalthert/precommit
      rev: v0.4.1
      hooks:
          - id: style-files
            args: [--style_pkg=styler, --style_fun=tidyverse_style]
          - id: parsable-R
          - id: no-browser-statement
          - id: no-debug-statement
          - id: lintr
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: check-added-large-files
            args: [--maxkb=200]
          - id: end-of-file-fixer
            exclude: \.Rd
    - repo: local
      hooks:
          - id: forbid-to-commit
            name: Don't commit common R artifacts
            entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
            language: fail
            files: \.(Rhistory|RData|Rds|rds)$
          # `exclude: <regex>` to allow committing specific files
