---
name: mthfr-and-friends
channels:
    - conda-forge
    - bioconda
    - r
    - nodefaults
dependencies:
    - snakemake
    - pre-commit
    - r-base
    - r-precommit
    - bioconda::bioconductor-stringdb
    - r-tidyverse
    - r-ggpubr
    - r-data.table
    - r-cowplot
    - r-ggupset
    - r-upsetr
